#!/bin/bash

muttdir="$HOME/.config/mutt/"

wipe () { rm $HOME/.offlineimaprc
rm -rf "$muttdir"/accounts
rm -f "$muttdir"credentials/*gpg
rm "$muttdir"personal.muttrc ;}

(dialog --defaultno --title "Wipe all custom neomutt/offlineIMAP settings?" --yesno "Would you like to wipe all of the mutt/offlineIMAP settings generated by the system?" 6 60 && wipe) || clear && exit

clear
